# Generated by Django 3.2.7 on 2021-09-28 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20210927_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tag',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.tag'),
        ),
    ]
